# PHZ1140C Vectors

## Tips

  * Use __esc r__ to disable a cell
  * Use __esc y__ to reactivate it
  * Use __esc m__ to go to markdown mode
  * Shift + return to execute a cell

Click [here](https://www.w3schools.com/python/default.asp) for an excellent Python online tutorial.

## Goal

The purpose of this notebook is to help you become familiar with vectors.

## What is a vector?

Many quantities in physics including __displacement__, __velocity__, and __force__ can be represented as vectors. 

Consider, for example, displacement. As the name implies, displacement has something to do with starting at one place and ending up somewhere else. Suppose you started in Tallahassee, Florida, and ended up in Atlanda, Georgia. Perhaps you flew from Tallahassee to Atlanta, or perhaps you decided to drive. Perhaps you first drove east on the I10 and then north on the I75; or perhaps you chose to drive on state roads and then join the I75 further north. 

There are many paths you could have taken to go from Tallahassee to Atlanta. But of all the paths between your starting and end points there is one that is the shortest. This is necessarily the straight line from your starting point to your end point. Of course, in reality, we can't take this path because a straight tunnel does not exist between Tallahassee and Atlanta! 

By definition, displacement is a mathematical object that represents the operation of starting from one point and ending at another by following a straight line between the two points. A displacement, therefore, has two attributes: a __magnitude__, in this case the straight line distance between the two points, and a __direction__. A __vector__ is a quantity that encodes a magnitude, which is always positive or zero, and a direction. 

## Representing and encoding a vector

Suppose that $v$ represents the magnitude of a vector. To remind us that a vector also has a direction, we use  $\vec{v}$ as the symbolic representation of the vector whose magnitude is $v$. Another conventon is to use bold type, $\boldsymbol{v}$, to represent a vector. To remind us that a magnitude cannot be negative, we sometimes represent the magnitude of a vector using the symbol $|\vec{v}|$ or $|\boldsymbol{v}|$. 

A conceptually appealing way of encoding the two attributes of a vector is as an arrow. The length of the arrow, which cannot be negative, is the magnitude, while the direction of the arrow is the direction of the vector. 

Another obvious 
way to encode, or represent, a vector is as a __tuple__, $(m, d)$, where $m$ is the magnitude and $d$ is the direction. For example, a velocity $\vec{v}$ could be encoded as follows:  $\vec{v} = (30 \text{ mph}, \text{$15^\text{o}$ East of North})$.

Vectors can be multiplied or divided by a number, that is, scaled. Suppose we multiply a vector by a positive factor $f$. We need to agree on what we want this to mean. Let's agree that this means we scale the *magnitude* of the vector by the factor $f$, while leaving the direction unchanged. This means that the new and old vectors would be parallel to each other since they are pointing in the same direction. Going back to our velocity example, this would mean that
the new vector $\vec{w}$ is given by
\begin{align}
    \vec{w} & = f \, \vec{v},\\
            & = (f \times 30 \text{ mph}, \text{$15^\text{o}$ East of North}).
\end{align}

Unfortunately, the equation above illustrates a problem with our tuple representation. Since we agree only to change the magnitude, we are forced to treat the first entry of the tuple differently from the second entry. There is another problem.

Notice that if we scale a vector by the inverse of its magnitude, that is, we compute $ \vec{v} \, / \, v$, then the resulting vector will have a magnitude of one and have the same direction as the vector $\vec{v}$. Moreover, the magnitude of the scaled vector will be dimensionless, that is, it will have no units. A dimensionless vector with a magnitude of one is called a __unit__ vector. It is represented with a symbol decorated with a "hat", e.g., $\hat{v}$. 

The third problem with our tuple representation of a vector is that the magnitude may or may not be dimensionless, while the direction is always dimensionless. 
Yet another problem with the tuple representation is that if we scale the vector by a negative number, $f$, our previous rule for creating a new vector no longer works because magnitudes cannot be negative! So we need to change our rule and scale the magnitude by the *absolute* value of the scale factor $f$, denoted by the symbol $|f|$. 

But what do we do with the negative sign? Well, let's suppose it makes sense to add and subtract vectors. Then, if $f = -1$, it is surely natural to require that $\vec{A} +  f \, \vec{A} = 0$. That makes a lot of sense. 

Suppose we go from point A to point B in a straight line, a displacement denoted by $\vec{D}$. Then going from B to A is a displacement in exactly the opposite direction. Therefore, it makes sense to interpret the vector $-\vec{D}$ as a vector of the same magnitude as $\vec{D}$ but pointing in exactly the opposite direction. Clearly, if I go from A to B and then B to A, my net displacement is zero because it is as if I haven't moved! Therefore, it makes sense that $\vec{D} - \vec{D} = 0$. In summary, if we scale a vector by the number $f$ our rule must be this: scale the magnitude by $|f|$, thereby keeping the magnitude positive, and leave the direction unchanged unless $f$ is negative in which case reverse the direction of the vector.

This rule is somewhat messy! It would be nice to find a representation of a vector, inspired by its arrow representation, which treats the magnitude and direction in a tidy, uniform, way.


## Vector algebra

There is such a representation, namely, an $n$-tuple, where for the vectors we'll be using $n = 3$. (Physicists, routinely deal with vectors in $n > 3$ dimensions, even $n = \infty$!) The key point about vectors, as alluded to, is that they can be manipulated algebraically. There exists an algebra of vectors. Vectors can be scaled, they can be added, subtracted, and multiplied. For example, if I go from point A to point B and then from point B to point C, it is the same as going from point A to C. Therefore, if $\vec{a}$ is the displacement from A to B, $\vec{b}$ the displacement from B to C and $\vec{c}$ the displacement from A to C, we define vector addition by

\begin{align}
\vec{c} & = \vec{a} + \vec{b}.
\end{align}

In terms of the arrow representation of vectors, this means an arrow with its tail at A and its head at B, another with its tail at B and its head at C, while the arrow that represents $\vec{c}$ has its tail at A and its head at C.

But now we come to a crucial observation about vector addition. Since a vector has two attributes only, magnitude and direction, we are free to move the vector around so long as it maintains its direction and its magnitude (think of moving arrows around while maintaining their directions). Therefore, we can go from A to C with a displacement along the vector $\vec{b}$ first and then with a displacement along the vector $\vec{a}$, that is, we can write

\begin{align}
\vec{c} & = \vec{b} + \vec{a}.
\end{align}

This shows that the addition of vectors behaves like the addition of numbers in that the operation of addition is commutative, e.g.: 2 + 3 = 3 + 2.

### Coordinate vectors

The fact that vectors can be added and subtracted suggests a better algebraic way to represent them. Suppose we have designated some point in space to be a marker with respect to which the positions of all other points are specified. The special marker is called the __origin__. Since the choice of origin is arbitrary, we are free to choose it as we see fit. For example, if we are modeling the orbits of the inner planets, we may choose the center of the Sun as the origin. If we are modeling a projectile, it may be more convenient to choose the launch position as the origin. At the origin, we erect three mutually orthogonal lines, that is, lines such that each is at right angles to the other two. Let's label these lines, each an axis, $x$, $y$, and $z$. This construct is called a __Cartesian coordinate system__. We need three axes because space has 3 dimensions. A space with $n$ dimensions needs $n$ axes.

Another way of thinking about the unit vectors is that they *define* the Cartesian coordinate system by specifying the directions of the three axes. Any point in space can be specified by giving three numbers, namely, the $x$, $y$, and $z$ coordinates with respect to the origin of the coordinate system along the directions specified by the associated unit vectors. There exist many coordinate systems. Since the surface of the Earth is 2-dimensional, we use a 2-dimensional coordinate system to specify a point on its surface. In special relativity, space and time are viewed as a 4-dimensional construct called spacetime. Any point in spacetime requires the specification of 4 numbers. 

A vector in 3-dimensional space can be represented by a 3-tuple. For example, the position of an object can be represented by a __position vector__  $\vec{r} = (x, y, z)$, which simply specifies the $x$, $y$, and $z$ coordinates of the object with respect to the chosen origin. Likewise, a velocity can be specified by giving three numbers $\vec{v} = (v_x, v_y, v_z)$. Since vectors can be scaled and added, we can write
\begin{align}
    \vec{r} & = x \, \hat{i} + y \, \hat{j} + z \, \hat{k}, \\
    \vec{v} & = v_x \, \hat{i} + v_y \, \hat{j} + v_z \, \hat{k}.
\end{align}
Since $\vec{r} = (x, y, z)$, it follows from the above that $\hat{i} = (1, 0, 0)$, 
$\hat{j} = (0, 1, 0)$, and $\hat{k} = (0, 0, 1)$. 

An important point to note is that if we change the coordinate system, the three numbers that represent a vector, that is, the __vector components__, will in general change. But the vector they represent remains the same; the vector will have the same magnitude and the same direction. In that sense, a vector is an object that is independent of the coordinate system. We say it is a coordinate-independent object. Vector components are used only because they are convenient way to define a vector, but in many physics problems it is possible to work with vectors without ever having to consider their components. 

### Import Modules 
Make Python modules (that is, collections of programs) available to this notebook.


In [1]:
import os, sys
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import sympy as sm
import scipy as sp
import pandas as pd
import vpython as vp
import itertools as it

sm.init_printing()        # activate "pretty printing" of symbolic expressions
%matplotlib inline

<IPython.core.display.Javascript object>

### Setup fonts

In [2]:
# update fonts
FONTSIZE = 14
font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : FONTSIZE}
mp.rc('font', **font)

# use latex if available on system, otherwise set usetex=False
mp.rc('text', usetex=True)

# set a seed to ensure reproducibility 
# on a given machine
seed = 314159
rnd  = np.random.RandomState(seed)

### numpy basics

In [3]:
# 1. creating arrays
a = np.array((1,2,3))
b = np.array((3,2,1))
a, b

(array([1, 2, 3]), array([3, 2, 1]))

In [4]:
# 2. compute a + b
c = a + b
c

array([4, 4, 4])

In [5]:
# 3. compute a*b
d = a * b
d

array([3, 4, 3])

In [6]:
# 4. compute sum(a*b)
f = np.sum(d)
f

10

In [7]:
# 5. divide a by 2
a2 = a / 2
a2

array([0.5, 1. , 1.5])

In [8]:
# 6. compute sqrt(a)
sqa = np.sqrt(a)
sqa

array([1.        , 1.41421356, 1.73205081])

In [9]:
# 7. compute outer product of a and b
ab = np.outer(a, b)
ab

array([[3, 2, 1],
       [6, 4, 2],
       [9, 6, 3]])

In [10]:
# 8. compute inner product of a and b
abi = np.inner(a, b)
abi

10

In [11]:
# 9. convert b to a 2d array of shape (3, 1)
b2 = b[:, np.newaxis]
b2, b2.shape

(array([[3],
        [2],
        [1]]),
 (3, 1))

10. compute $a - b2$ and try to explain the result.

In [12]:
# 10. compute a - b2
ab2 = a - b2
ab2

array([[-2, -1,  0],
       [-1,  0,  1],
       [ 0,  1,  2]])

In [13]:
# 11. compute cos(a)
cosa = np.cos(a)
cosa

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [14]:
# 12. compute acos(a) and convert the angles from radians to degrees
acosa = np.arccos(cosa) * 180 / np.pi
acosa

array([ 57.29577951, 114.59155903, 171.88733854])

## Exercise 1

#### Dot product
Given vectors $\vec{A} = (A_x, A_y, A_z)$ and $\vec{B} = (B_x, B_y, B_z)$ with components defined with respect to some coordinate system, the __dot product__ between them is 
\begin{align}
    \vec{A} \cdot \vec{B} & = A_x B_x + A_y B_y + A_z B_z.
\end{align}
At face value, this formula suggests that the dot product depends on the vector components and consequently on the coordinate system that is used to define them. In fact, the dot product is independent of the coordinate system. Try to show this by proving that  the dot product can be expressed as
\begin{align}
    \vec{A} \cdot \vec{B} & = A B \cos(\theta),
\end{align}
where $A$ and $B$ are the magnitudes and $\theta$ is the angle between the vectors. Since neither the magnitudes nor the angle between the vectors depend on the coordinate system, it follows that the dot product is likewise independent of the coordinate system. Therefore, we can use the first form of the dot product because it will give the same answer in all coordinate systems.

#### Magnitude
The magnitude of a vector is given by $A = \sqrt{ \vec{A} \cdot \vec{A}}$.

### Exercise details
Create two vectors $\vec{A} = (2,3,6)$ and $\vec{B}=(6,4,12)$ then answer the following questions
 
  1. Compute the magnitude of each vector
  2. Compute the unit vectors associated with each vector
  3. Compute the dot product between the vectors using their components
  4. Compute the angle between the vectors in radians
  6. Compute $\vec{C} = A + B$
  7. Compute the dot product of $\vec{C}$ with itself
  8. Compute $A^2 + B^2 + 2\vec{A}\cdot\vec{B}$. How does this compare with $C^2$?
  9. Compute a vector $\vec{D}$ that is perpendicular to $\vec{A}$, which starts from the head of vector $\vec{B}$ and which touches the vector $\vec{A}$. Compute the dot product of this new vector with $\vec{A}$. What value should you get?
  



[1]
! Missing $ inserted.
<inserted text> 
                $
l.492 is, we compute \$ \vec
                            {v} , / , v\$, then the resulting vector will have
? 
! Emergency stop.
<inserted text> 
                $
l.492 is, we compute \$ \vec
                            {v} , / , v\$, then the resulting vector will have
Output written on notebook.pdf (1 page).
Transcript written on notebook.log.
