# Vectors - Solutions
> Harrison B. Prosper<br>
> Created September 2023 PHY1140C

## Tips

  * Use __esc r__ to disable a cell
  * Use __esc y__ to reactivate it
  * Use __esc m__ to go to markdown mode
  * Shift + return to execute a cell

Click [here](https://www.w3schools.com/python/default.asp) for an excellent Python online tutorial.

## Goal

The purpose of this notebook is to help you become familiar with vectors.

## What is a vector?

Many quantities in physics including __displacement__, __velocity__, and __force__ can be represented as vectors. 

Consider, for example, displacement. As the name implies, displacement has something to do with starting at one place and ending up somewhere else. Suppose you started in Tallahassee, Florida, and ended up in Atlanda, Georgia. Perhaps you flew from Tallahassee to Atlanta, or perhaps you decided to drive. Perhaps you first drove east on the I10 and then north on the I75; or perhaps you chose to drive on state roads and then join the I75 further north. 

There are many paths you could have taken to go from Tallahassee to Atlanta. But of all the paths between your starting and end points there is one that is the shortest. This is the straight line from your starting point to your end point. In practice, we can't take this path because a straight tunnel does not exist between Tallahassee and Atlanta! 

By definition, displacement is a mathematical object that represents the operation of starting at one point and ending at another by following the straight line between the two points. A displacement, therefore, has two attributes: a __magnitude__, in this case the straight-line distance between the two points, and a __direction__. A __vector__ is a quantity that encodes a magnitude, which is always positive or zero, and a direction. 

## Representing and encoding a vector

Suppose that $v$ represents the magnitude of a vector. To remind us that a vector also has a direction, we use  $\vec{v}$ as the symbolic representation of the vector whose magnitude is $v$. Another conventon is to use bold type, $\vec{v}$, to represent a vector. To remind us that a magnitude cannot be negative, we sometimes represent the magnitude of a vector using the symbol $|\vec{v}|$ or $|\vec{v}|$. 

An arrow is a conceptually, and visually, appealing way of encoding the two attributes of a vector. The length of the arrow, which obviously can't be negative, is the magnitude, while the direction of the arrow is the direction of the vector. 

Another obvious 
way to encode, or represent, a vector is as a __tuple__, $(m, d)$, where $m$ is the magnitude and $d$ is the direction. (In mathematics, an $n$-tuple, $(x_1,\cdots, x_n)$, is an ordered sequence of entities $x_1$ to $x_n$ that are to be viewed as a single entity.) For example, a velocity $\vec{v}$ could be encoded as follows:  $\vec{v} = (30 \text{ mph}, \text{$15^\text{o}$ East of North})$.

Vectors can be multiplied or divided by a number, that is, scaled. Suppose we multiply a vector by a positive number $f$. We need to agree on what we want this to mean. Let's agree that this means we scale the *magnitude* of the vector by the number $f$, while leaving the direction unchanged. This means that the new and old vectors would be parallel to each other since they are pointing in the same direction. Going back to our velocity example, this would mean that
the new vector $\vec{w}$ is given by
\begin{align}
    \vec{w} & = f \, \vec{v},\nonumber\\
            & = (f \times 30 \text{ mph}, \text{$15^\text{o}$ East of North}).
\end{align}
Unfortunately, the equation above illustrates a problem with our tuple representation. Since we agree only to change the magnitude, we are forced to treat the first entry of the tuple differently from the second entry. There is another problem.

Notice that if we scale a vector by the inverse of its magnitude, that is, we compute $\vec{v} / v$, then the resulting vector will have a magnitude of one and have the same direction as the vector $\vec{v}$. Moreover, the magnitude of the scaled vector will be dimensionless, that is, it will have no units. A dimensionless vector with a magnitude of one is called a __unit__ vector. It is represented with a symbol decorated with a "hat", e.g., $\hat{v}$. 

The third problem with our tuple representation of a vector is that the magnitude may or may not be dimensionless, while the direction is always dimensionless. 
Yet another problem with the tuple representation is that if we scale the vector by a negative number, $f$, our previous rule for creating a new vector no longer works because magnitudes cannot be negative! So we need to change our rule and scale the magnitude by the *absolute* value of the scale factor $f$, denoted by the symbol $|f|$. 

But what do we do with the negative sign? Well, let's suppose it makes sense to add and subtract vectors. Then, if $f = -1$, it is surely natural to require that $\vec{A} +  f \, \vec{A} = 0$. That $\vec{A} - \vec{A} = 0$ surely makes a lot of sense. But what precisely does it mean?

Suppose we go from point A to point B in a straight line, a displacement we'll denote by $\vec{D}$. If now we go from B to A that is a displacement in exactly the opposite direction to $\vec{D}$. Therefore, it makes sense to interpret the vector $-\vec{D}$ as a vector of the same magnitude as $\vec{D}$ but pointing in exactly the opposite direction. Clearly, if I go from A to B and then B to A, my net displacement is zero because it is as if I haven't moved! Therefore, it indeed makes sense that $\vec{D} - \vec{D} = 0$. In summary, if we scale a vector by the number $f$ our rule must be this: scale the magnitude by $|f|$, that is, a positive number, thereby keeping the magnitude positive, but leave the direction unchanged unless $f$ is negative in which case reverse the direction of the vector.

This rule is a bit messy! It would be nice to find a representation of a vector, inspired by its arrow representation, which treats the magnitude and direction in a tidy, uniform, way.


## Vector algebra

There is such a representation, namely, an $n$-tuple, where for the vectors we'll be using $n = 3$. (Physicists, routinely deal with vectors in $n > 3$ dimensions, even $n = \infty$!) The key point about vectors, as alluded to, is that they can be manipulated algebraically, that is, there exists an algebra of vectors. Vectors can be scaled, they can be added, subtracted, and multiplied. For example, if I go from point A to point B and then from point B to point C, it is the same as going from point A to C. Therefore, if $\vec{a}$ is the displacement from A to B, $\vec{b}$ the displacement from B to C and $\vec{c}$ the displacement from A to C, we define vector addition by
\begin{align}
\vec{c} & = \vec{a} + \vec{b}.
\end{align}
In terms of the arrow representation of vectors, this means we start with an arrow whose tail is at A and its head at B, another with its tail at B and its head at C, while the arrow that represents $\vec{c}$ has its tail at A and its head at C, as depicted in the figure to the left.
<img src="fig01_vector.png" align="left" alt="vector adddition" width="200"/>
But now we come to a crucial observation about vector addition. Since a vector has two attributes only, magnitude and direction, we are free to move the vector around so long as it maintains its direction and its magnitude (think of moving the arrows around while maintaining their directions). Therefore, we can go from A to C with a displacement along the vector $\vec{b}$ first followed by a displacement along the vector $\vec{a}$, as shown in the figure to the right.
<br clear="left"/>

<img src="fig02_vector.png" align="right" alt="vector adddition" width="200"/>
Obviously, we won't go via point B, but we'll arrive at the same place, namely, point C. This sequence of vector operations corresponds to the vector addition
\begin{align}
\vec{c} & = \vec{b} + \vec{a}.
\end{align}
This shows that the addition of vectors behaves like the addition of numbers in that the operation of addition is commutative, e.g.: 2 + 3 = 3 + 2.
<br clear="right"/>

### Coordinate vectors

The fact that vectors can be added and subtracted suggests a better algebraic way to represent them. Suppose we have designated some point in space to be a marker with respect to which the positions of all other points are specified. The special marker is called the __origin__. Since the choice of origin is arbitrary, we are free to choose it as we see fit. For example, if we are modeling the orbits of the inner planets, we may choose the center of the Sun as the origin. If we are modeling a projectile, it may be more convenient to choose the launch position as the origin. At the origin, we erect three mutually orthogonal lines, that is, lines such that each is at right angles to the other two. Let's label these lines, each an axis, $x$, $y$, and $z$. This construct is called a __Cartesian coordinate system__. We need three axes because space has 3 dimensions. A space with $n$ dimensions needs $n$ axes.

Another way of thinking about the unit vectors is that they *define* the Cartesian coordinate system by specifying the directions of its three axes, as depicted in the figure.
<img src="fig03_cartesian.png" align="left" alt="Cartesian coordinate system" width="200"/>
The location of any point in 3-dimensional space can be specified by a 3-tuple $(x, y, z)$, where $x$, $y$, and $z$ are called the __coordinates__ of the point with respect to the origin of the chosen coordinate system along the directions specified by the associated unit vectors. The 3-tuple specifies, or defines, a __position vector__, $\vec{r} = (x, y, z)$. An example of a widely used Cartesian coordinate system is the __heliocentric ecliptic coordinate system__, which is shown here.
<img src="fig04_heliocentric.png" align="right" alt="heliocentric coordinate system" width="400"/>
The center of this coordinate system is near the center of the Sun. In fact, the origin of this coordinate system is (by [international agreement](https://en.wikipedia.org/wiki/International_Celestial_Reference_System_and_its_realizations)) at the center of mass of the Solar System.

Like position in 3-dimensional space, a velocity can also be specified by giving three numbers $\vec{v} = (v_x, v_y, v_z)$, where $v_x$, $v_y$, and $v_z$ are the components of the velocity in the $\hat{i}$, $\hat{j}$, and $\hat{k}$ directions, respectively. 
If we represent the three unit vectors as $\hat{i} = (1, 0, 0)$, 
$\hat{j} = (0, 1, 0)$, and $\hat{k} = (0, 0, 1)$, we can write position and velocity as
\begin{align}
    \vec{r} & = x \, \hat{i} + y \, \hat{j} + z \, \hat{k}, \\
    \vec{v} & = v_x \, \hat{i} + v_y \, \hat{j} + v_z \, \hat{k}.
\end{align}
But remember the above expressions remain true regardless of the specific coordinate representations of the vectors.

As noted above, vectors (if you think of them as arrows) can be moved around. This is true also of the position vector. But, by convention, we agree to fix the tail end of the position vector at the origin.
<br clear="right"/>

An important point to note is that if we change the coordinate system (perhaps it it rotated), the three numbers that represent a vector, that is, the __vector components__, will, in general, change. But the vector they represent remains the same: it has same magnitude and the same direction. A vector is said to be a __coordinate-independent__ object. Even though physicists almost always use coordinate systems for calculations, we prefer to use them with coordinate-independent objects such as vectors so that we obtain results that do not depend on the arbitrarily chosen coordinate system. After all, Nature doesn't care about artifacts such as coordinate systems! Vector components are used only because they are a convenient way to define, or represent, a vector, but in many physics problems it is possible to work with vectors without ever having to consider their components. In one of the problems below, you'll be invited to work out a coordinate-independent formula for a new vector from two other vectors.

### Import Modules 
Make Python modules (that is, collections of programs) available to this notebook.


In [2]:
import os, sys
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import sympy as sm
import scipy as sp
#import pandas as pd
#import vpython as vp
#import itertools as it

sm.init_printing()        # activate "pretty printing" of symbolic expressions
%matplotlib inline

### Setup fonts

In [3]:
# update fonts
FONTSIZE = 14
font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : FONTSIZE}
mp.rc('font', **font)

# use latex if available on system, otherwise set usetex=False
mp.rc('text', usetex=True)

# set a seed to ensure reproducibility 
# on a given machine
seed = 314159
rnd  = np.random.RandomState(seed)

## Vector Basics

### Dot product
Given vectors $\vec{A} = (A_x, A_y, A_z)$ and $\vec{B} = (B_x, B_y, B_z)$ with components defined with respect to some coordinate system, the __dot product__ between them is 
\begin{align}
    \vec{A} \cdot \vec{B} & = A_x B_x + A_y B_y + A_z B_z.
\end{align}
At face value, this formula suggests that the dot product depends on the vector components and consequently on the coordinate system that is used to define them. In fact, the dot product is independent of the coordinate system. Try to show this by proving that  the dot product can be expressed as
\begin{align}
    \vec{A} \cdot \vec{B} & = A B \cos(\theta),
\end{align}
where $A$ and $B$ are the magnitudes (see below) and $\theta$ is the angle between the vectors. Since neither the magnitudes nor the angle between the vectors depend on the coordinate system, it follows that the dot product is likewise coordinate independent. Therefore, if we use the first form of the dot product, we'll always get the same answer whatever coordinate system we use. 

### Magnitude
The magnitude of a vector, $\vec{A}$, is defined by 
\begin{align}
A & = \sqrt{ \vec{A} \cdot \vec{A}}, \\
    & = \sqrt{A_x^2 + A_y^2 + A_z^2} .
\end{align}
What ancient theorem does this remind you of?

### Cross product
Given two vectors $\vec{A}$ and $\vec{B}$ the cross product creates another vector $\vec{C}$ defined by
\begin{align}
    \vec{C} & = \vec{A} \times \vec{B},\\
            & = A B \sin(\theta) \, \hat{n},
\end{align}
where $\hat{n}$ is a unit vector that is perpendicular to the plane containing $\vec{A}$ and $\vec{B}$. But this leaves a twofold ambiguity in the orientation of $\hat{n}$, which can be resolved as follows.
With your right hand do the following.

   1. Point your fingers in the direction of vector $\vec{A}$, the vector to the left in the cross product.
   2. Curl your fingers into the direction of vector $\vec{B}$. If you can't, you must rotate your wrist by about 180$^\text{o}$ (yes, this can be quite awkward) and start again with step 1. 
   3. The direction in which your thumb is pointing gives the correct orientation of $\hat{n}$.

The rule above is called the __right-hand rule__. Remember it; you'll use it many times over the next few years. Like the dot product, the cross product is coordinate-independent. But unlike the dot product, the cross product is non-commutative: $\vec{A} \times \vec{B} \neq \vec{B} \times \vec{A}$.

## Numpy Basics

An __array__ is an ordered sequence of objects. For example, [1,2,3,4] is a 1-dimensional array of integers; [[1.5,2.7,3.141,4.2], [0.5,0.1,9.1,3.6]] is an example of a 2-dimensional array of real numbers. 
__numpy__ is the standard software module for manipulating arrays of numbers in Python. The best way to learn numpy and any software is to use it! Work through the following simple examples and try to understand what is being done. Feel free to change the examples to test your understanding. 

Then work on __Exercise 1__.

In [4]:
# 1. creating arrays
a = np.array((1,2,3))
b = np.array((3,2,1))
a, b

(array([1, 2, 3]), array([3, 2, 1]))

In [5]:
# 2. compute a + b
c = a + b
c

array([4, 4, 4])

In [6]:
# 3. compute a*b
d = a * b
d

array([3, 4, 3])

In [7]:
# 4. compute sum(a*b)
f = np.sum(d)
f

10

In [8]:
# 5. divide a by 2
a2 = a / 2
a2

array([0.5, 1. , 1.5])

In [9]:
# 6. compute sqrt(a)
sqa = np.sqrt(a)
sqa

array([1.        , 1.41421356, 1.73205081])

In [10]:
# 7. compute outer product of a and b
ab = np.outer(a, b)
a,b,ab

(array([1, 2, 3]),
 array([3, 2, 1]),
 array([[3, 2, 1],
        [6, 4, 2],
        [9, 6, 3]]))

In [11]:
# 8. compute inner product of a and b
abi = np.inner(a, b)
abi

10

In [12]:
# 9. convert b to a 2d array of shape (3, 1)
b2 = b[:, np.newaxis]
b2, b2.shape

(array([[3],
        [2],
        [1]]),
 (3, 1))

10. compute $a - b2$ and try to explain the result.

In [13]:
# 10. compute a - b2
ab2 = a - b2
ab2

array([[-2, -1,  0],
       [-1,  0,  1],
       [ 0,  1,  2]])

The following replicates the operations that led to the result above.

In [14]:
def print_array(name, myarray):
    print(f'{name:s}, shape: {str(myarray.shape):s}\n{str(myarray):s}\n')
    
# 1. make a into a 2D array of shape (1, 3)
a2 = a[np.newaxis, :]
print_array('a2', a2)

# 2. extend a2 vertically, that is, along axis 0, by repeating the row 3 times
aa = np.repeat(a2, 3, axis=0)
print_array('aa', aa)

# 3. extend b2 horizontally, that is, along axis 1, by repeating the column 3 times
print_array('b2', b2)

bb = np.repeat(b2, 3, axis=1)
print_array('bb', bb)

# 4. now perform an element-wise subtraction aa - bb
print_array('aa - bb', aa-bb)

a2, shape: (1, 3)
[[1 2 3]]

aa, shape: (3, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]]

b2, shape: (3, 1)
[[3]
 [2]
 [1]]

bb, shape: (3, 3)
[[3 3 3]
 [2 2 2]
 [1 1 1]]

aa - bb, shape: (3, 3)
[[-2 -1  0]
 [-1  0  1]
 [ 0  1  2]]



In [15]:
# 11. compute cos(a)
cosa = np.cos(a)
cosa

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [16]:
# 12. compute acos(a) and convert the angles from radians to degrees
acosa = np.arccos(cosa) * 180 / np.pi
acosa

array([ 57.29577951, 114.59155903, 171.88733854])

In [17]:
# 13. compute dot product a . b
adotb = np.dot(a, b)
adotb

10

In [18]:
# 14. compute cross product a x b
acrossb = np.cross(a, b)
acrossb

array([-4,  8, -4])

In [19]:
# 15. compute cross product of b x a
bcrossa = np.cross(b, a)
bcrossa

array([ 4, -8,  4])

In [20]:
# 16. compute dot product of a and a x b
adot_axb = np.dot(a, acrossb)
adot_axb

0

## Exercise 1
Create two vectors $\vec{A} = (2,3,6)$ and $\vec{B}=(6,4,12)$ using the __numpy__ Python module and then answer the following questions. Once the vectors are created, do not work with their components but do everything using __numpy__ operations.
 
  1. Compute the magnitude of each vector.
  2. Compute the unit vectors associated with each vector.
  3. Compute the dot product between the vectors using their components.
  4. Compute the angle between the vectors in radians.
  6. Compute $\vec{C} = \vec{A} + \vec{B}$.
  7. Compute the dot product of $\vec{C}$ with itself.
  8. Compute $A^2 + B^2 + 2\vec{A}\cdot\vec{B}$. How does this compare with $C^2$?
  9. Compute a vector $\vec{D}$ that is perpendicular to $\vec{A}$. First derive a coordinate-independent formula for $\vec{D}$. (*Hint*: draw a picture with the three vectors represented as arrows.) The vector $\vec{D}$ should start from the vector $\vec{A}$ and touch the head of vector $\vec{B}$. What value should you get if you compute the dot product of $\vec{D}$  with $\vec{A}$? Verify your answer to four significant figures.
  10. Compute the vector $\vec{D}$, but this time use cross products (and, at most, a single dot product). (*Hint*: use the right hand rule, starting with $\vec{B} \times \vec{A}$.)
  


### Solutions

In [21]:
A = np.array((2,3,6))
B = np.array((6,4,12))
A, B

(array([2, 3, 6]), array([ 6,  4, 12]))

1. Compute the magnitude of each vector.

$|\vec{A}| = \sqrt{\vec{A}\cdot\vec{A}}$

In [22]:
def magnitude(a):
    return np.sqrt(np.dot(a, a))
    
a = magnitude(A)
b = magnitude(B)
a, b

2. Compute the unit vectors associated with each vector.

$\hat{A} = \vec{A} / |\vec{A}|$

In [23]:
A_hat = A / a
B_hat = B / b
A_hat, B_hat, magnitude(A_hat), magnitude(B_hat)

(array([0.28571429, 0.42857143, 0.85714286]),
 array([0.42857143, 0.28571429, 0.85714286]),
 0.9999999999999999,
 0.9999999999999999)

3. Compute the dot product between the vectors using their components.

$\vec{A}\cdot\vec{B} = A_x B_x + A_y B_y + A_z B_z$

In [25]:
AdotB = np.sum(A * B)
AdotB

96

4. Compute the angle between the vectors in radians.

$\vec{A}\cdot\vec{B} = A B \cos(\theta)$, therefore,

$\theta = \cos^{-1}(\vec{A}\cdot\vec{B}/(|\vec{A}| |\vec{B}|))$

In [26]:
theta   = np.arccos(AdotB/a/b)
degrees = theta * 180 / np.pi
print(f'angle between A and B: {theta:4.2f} radians, {degrees:4.1f} degrees')

angle between A and B: 0.20 radians, 11.6 degrees


5. Compute $\vec{C} = \vec{A} + \vec{B}$.

In [27]:
C = A + B
A, B, C

(array([2, 3, 6]), array([ 6,  4, 12]), array([ 8,  7, 18]))

6. Compute the dot product of $\vec{C}$ with itself.

In [28]:
C2 = np.dot(C, C)
C2

437

7. Compute $A^2 + B^2 + 2\vec{A}\cdot\vec{B}$. How does this compare with $C^2$?

In [29]:
F = a**2 + b**2 + 2*AdotB
C2, F

(437, 437.0)

8. Compute a vector $\vec{D}$ that is perpendicular to $\vec{A}$. First derive a coordinate-independent formula for $\vec{D}$. (*Hint*: draw a picture with the three vectors represented as arrows.)
<img src="fig05_vectors_A_B_D.png" align="left" alt="vector adddition 2" width="200"/>
The vector $\vec{D}$ should start from the vector $\vec{A}$ and touch the head of vector $\vec{B}$. What value should you get if you compute the dot product of $\vec{D}$  with $\vec{A}$? Verify your answer to four significant figures.
<br clear="left"/>

In the figure above, consider the vector from point O to point P. We'll call this vector $\vec{E}$. Note that $\vec{E} + \vec{D} = \vec{B}$, therefore, $\vec{D} = \vec{B} - \vec{E}$. Note also that $\vec{E}$ has magnitude $|B\cos(\theta)|$. $\vec{E}$ is also parallel to $\vec{A}$. Therefore, we can write 
\begin{align}
    \vec{E} & = \left( \frac{ \vec{A} }{  |\vec{A}| } \right) 
    \left( \frac{\vec{A} \cdot  \vec{B} } { |\vec{A} |} \right).
\end{align}
Consequently, given that $|\vec{A}|^2 = \vec{A} \cdot \vec{A}$,
\begin{align}
    \vec{D} & = \vec{B} - \frac{ \vec{A} (\vec{A} \cdot \vec{B}) } { \vec{A} \cdot \vec{A} }, \\
        &= \frac{\vec{B} (\vec{A} \cdot \vec{A}) - \vec{A} (\vec{A} \cdot \vec{B}) } { \vec{A} \cdot \vec{A} } .
\end{align}

In [30]:
AA = np.dot(A, A)
AB = np.dot(A, B)
D  = (B * AA - A * AB)/AA
DA = np.dot(D, A)
print(f'D dot A: {DA:10.4f}')

# from the figure, we expect the magnitude of D to be B*sin(theta)
d = magnitude(D)
y = b * np.sin(theta)
print(f'{d:10.2f}, {y:10.2f}')

D

D dot A:    -0.0000
      2.81,       2.81


array([ 2.08163265, -1.87755102,  0.24489796])

9. Compute the vector $\vec{D}$, but this time use cross products (and, at most, a single dot product). (*Hint*: use the right hand rule, starting with $\vec{B} \times \vec{A}$.)

Following the hint, we first compute $\vec{C} = \vec{B} \times \vec{A}$. The vector $\vec{C}$ has magnitude $|\vec{A}||\vec{B}|\sin(\theta)$, is perpendicular to both $\vec{B}$ and $\vec{A}$, and, from the right-hand rule, points out of the page.

We want a vector that is at right angles to, and points away from, $\vec{A}$. Since $\vec{A}$ and $\vec{C}$ are perpendicular, a vector perpendicular to both $\vec{A}$ and $\vec{C}$ necessarily lies in the plane formed by $\vec{B}$ and $\vec{A}$.

This suggests forming the vector $\vec{Q} = \vec{A} \times \vec{C}$. According to the right-hand rule, $\vec{Q}$ points away from $\vec{A}$ towards $\vec{B}$. Therefore, $\vec{Q}$ is in the same direction as $\vec{D}$. So all we need to do is adjust the magnitude to $\vec{Q}$ to get $\vec{D}$. The magitude of $\vec{Q}$ is $|\vec{A}| |\vec{C}|\sin(\pi/2) = |\vec{A}|^2|\vec{B}|\sin(\theta)$, that is, $(\vec{A}\cdot\vec{A})|\vec{B}|\sin(\theta)$. We, therefore, conclude that 
\begin{align}
\vec{D} &= \frac{\vec{Q}} {\vec{A}\cdot\vec{A}},\nonumber\\
                & = \frac{\vec{A} \times \vec{C}} {\vec{A}\cdot\vec{A}},\nonumber\\
               &= \frac{\vec{A} \times (\vec{B} \times \vec{A})} {\vec{A}\cdot\vec{A}} .
\end{align}

In [31]:
D1 = np.cross(A, np.cross(B, A)) / np.dot(A, A)

# compare with previous result for D
D, D1, D-D1

(array([ 2.08163265, -1.87755102,  0.24489796]),
 array([ 2.08163265, -1.87755102,  0.24489796]),
 array([0., 0., 0.]))