# Vectors: Solutions
> Harrison B. Prosper

## Tips

  * Use __esc r__ to disable a cell
  * Use __esc y__ to reactivate it
  * Use __esc m__ to go to markdown mode
  * Shift + return to execute a cell

Click [here](https://www.w3schools.com/python/default.asp) for an excellent Python online tutorial.

### Import Modules 
Make Python modules (that is, collections of programs) available to this notebook.


In [1]:
import os, sys
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
import sympy as sm
import scipy as sp
#import pandas as pd
#import vpython as vp
#import itertools as it

sm.init_printing()        # activate "pretty printing" of symbolic expressions
%matplotlib inline

### Setup fonts

In [2]:
# update fonts
FONTSIZE = 14
font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : FONTSIZE}
mp.rc('font', **font)

# use latex if available on system, otherwise set usetex=False
mp.rc('text', usetex=True)

# set a seed to ensure reproducibility 
# on a given machine
seed = 314159
rnd  = np.random.RandomState(seed)

## Exercise 1
Create two vectors $\vec{A} = (2,3,6)$ and $\vec{B}=(6,4,12)$ using the __numpy__ Python module and then answer the following questions. Once the vectors are created, do not work with their components but do everything using __numpy__ operations.
 
  1. Compute the magnitude of each vector.
  2. Compute the unit vectors associated with each vector.
  3. Compute the dot product between the vectors using their components.
  4. Compute the angle between the vectors in radians.
  6. Compute $\vec{C} = \vec{A} + \vec{B}$.
  7. Compute the dot product of $\vec{C}$ with itself.
  8. Compute $A^2 + B^2 + 2\vec{A}\cdot\vec{B}$. How does this compare with $C^2$?
  9. Compute a vector $\vec{D}$ that is perpendicular to $\vec{A}$. First derive a coordinate-independent formula for $\vec{D}$. (*Hint*: draw a picture with the three vectors represented as arrows.) The vector $\vec{D}$ should start from the vector $\vec{A}$ and touch the head of vector $\vec{B}$. What value should you get if you compute the dot product of $\vec{D}$  with $\vec{A}$? Verify your answer to four significant figures.
  10. Compute the vector $\vec{D}$, but this time use cross products (and, at most, a single dot product). (*Hint*: use the right hand rule, starting with $\vec{B} \times \vec{A}$.)
  


## Vector identities
1. $\vec{A} \times (\vec{B} \times \vec{C}) = (\vec{A} \times \vec{B} ) \times \vec{C}$

2. $\vec{A} \times (\vec{B} \times \vec{C}) = \vec{B}(\vec{A}\cdot\vec{C}) - \vec{C} (\vec{A}\cdot\vec{B})$

In [3]:
# Three random vectors
A = np.array([np.random.normal(0, 10), np.random.normal(0, 10), np.random.normal(0, 10)])
B = np.array([np.random.normal(0, 10), np.random.normal(0, 10), np.random.normal(0, 10)])
C = np.array([np.random.normal(0, 10), np.random.normal(0, 10), np.random.normal(0, 10)])
A, B, C

(array([  0.29048675, -15.35113016,  -1.82855168]),
 array([ 4.411309  , -0.017592  , 15.90737447]),
 array([ 5.95691615,  4.89154721, -4.90734978]))

In [4]:
E = B*np.dot(A, C) - C*np.dot(A, B)
E

array([ -120.00160533,   135.82620588, -1159.35724422])